volumes:
  pg_data:
  static:
  media:

services:
  postgres:
    container_name: postgres
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -p 5432 -q"]
      interval: 5s
      timeout: 2s
      retries: 3
  backend:
    container_name: backend
    image: jalambakisa/kittygram_backend
    env_file: .env
    volumes:
      - media:/app/media/
    depends_on:
      postgres:
        condition: service_healthy
  frontend:
    container_name: frontend
    env_file: .env
    image: jalambakisa/kittygram_frontend
  gateway:
    container_name: gateway
    image: jalambakisa/kittygram_gateway
    ports:
      - "80:80"
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - frontend
      - backend